"""add movie lists

Revision ID: 57224eff9369
Revises: faeca19a6ed2
Create Date: 2026-09-07 15:45:15.112100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '57224eff9369'
down_revision: Union[str, None] = 'faeca19a6ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_lists',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_movie_lists_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_lists'))
    )
    op.create_index(op.f('ix_movie_lists_created_by_id'), 'movie_lists', ['created_by_id'], unique=False)
    op.create_table('movie_list_items',
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('position >= 0', name=op.f('ck_movie_list_items_position_nonnegative')),
    sa.ForeignKeyConstraint(['list_id'], ['movie_lists.id'], name=op.f('fk_movie_list_items_list_id_movie_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_list_items_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'movie_id', name=op.f('pk_movie_list_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_list_items')
    op.drop_index(op.f('ix_movie_lists_created_by_id'), table_name='movie_lists')
    op.drop_table('movie_lists')
    # ### end Alembic commands ###
